Use resin-u-boot bbclass
resin-os/resin-ts pull request #69
Opened 2017-03-02 14:34 UTC by floion

2017-03-03 08:28 UTC, agherzan commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/0004-Replace-default-sd-bootargs.patch
> ++		"setenv bootargs root=/dev/mmcblk1p1 rootwait rw console=ttymxc0,115200 enable_wait_mode=off; " \
we would probably want this ro though.

2017-03-03 08:31 UTC, agherzan requested changes

2017-03-03 08:31 UTC, agherzan commented on layers/meta-resin-ts/recipes-core/systemd/systemd_%.bbappend
> +do_install_append_ts4900() {
Can you please reference the commit where this mistake was included?

2017-03-03 08:31 UTC, agherzan commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/ts4900-integrate-with-resin-configuration.patch
> ++		"else run emmcboot; " \
This looks badly indented.

2017-03-03 08:49 UTC, floion commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/ts4900-integrate-with-resin-configuration.patch
> ++		"else run emmcboot; " \
I indented like this for clarity.
Please paste the way you want it indented

2017-03-03 09:14 UTC, agherzan commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/ts4900-integrate-with-resin-configuration.patch
> ++		"else run emmcboot; " \
What if is this else supposed to be part of?

2017-03-03 09:39 UTC, floion commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/0004-Replace-default-sd-bootargs.patch
> ++		"setenv bootargs root=/dev/mmcblk1p1 rootwait rw console=ttymxc0,115200 enable_wait_mode=off; " \
The rootfs is remounted ro later on in the boot process

2017-03-03 09:41 UTC, floion commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/ts4900-integrate-with-resin-configuration.patch
> ++		"else run emmcboot; " \
if test ${jpsdboot} = 'off'

2017-03-03 10:45 UTC, michal-mazurek approved these changes

2017-03-03 21:35 UTC, telphan commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/0004-Replace-default-sd-bootargs.patch
> ++		"setenv bootargs root=/dev/mmcblk1p1 rootwait rw console=ttymxc0,115200 enable_wait_mode=off; " \
Still, why not mount it ro here?

2017-03-04 04:19 UTC, floion commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/0004-Replace-default-sd-bootargs.patch
> ++		"setenv bootargs root=/dev/mmcblk1p1 rootwait rw console=ttymxc0,115200 enable_wait_mode=off; " \
Because that change has no effect.
If there is consensus to change it though, I will.
@agherzan what is the decision here?

2017-03-04 04:19 UTC, floion commented on layers/meta-resin-ts/recipes-core/systemd/systemd_%.bbappend
> +do_install_append_ts4900() {
Done

2017-03-04 06:02 UTC, agherzan commented on layers/meta-resin-ts/recipes-bsp/u-boot/u-boot-ts/0004-Replace-default-sd-bootargs.patch
> ++		"setenv bootargs root=/dev/mmcblk1p1 rootwait rw console=ttymxc0,115200 enable_wait_mode=off; " \
We don't have that in the specification. It was just an idea. Don't think it's that important at this point.

2017-03-04 06:04 UTC, agherzan approved these changes

2017-03-04 06:53 UTC, telphan approved these changes

2017-03-06 04:20 UTC, merged